version: '3.8'

services:
  web:
    build: .
    image: habtes24/test1:latest  # Updated to match your Docker Hub repository
    ports:
      - "5100:5100"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydatabase  # Connection string for Flask to connect to PostgreSQL
    depends_on:
      - db  # Ensures that the 'db' service starts before the 'web' service
    command: python app.py  # Start Flask app

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist database data

volumes:
  db_data:  # Named volume to persist PostgreSQL data
